on:
  push:
    branches:
      - main
name: CI/CD

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jeanazabache/ghactions:${{ github.sha }}

  deploy-to-cluster:
    name: Deploy to Kubernetes Cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Set Kubernetes context from DigitalOcean
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s/deployment.yaml
          kubectl apply -f ./k8s/service.yaml

      - name: Update image in deployment
        run: |
          kubectl -n prueba set image --record deployment/prueba-gha prueba-gha=pablokbs/prueba-gha:${{ github.sha }}

      - name: Verify deployment
        run: |
          kubectl -n prueba rollout status deployment/prueba-gha
